client:
  hw_type: LD
  outputDirectory: /home/hgcal_dev/data/320-ML-F3TC-TT-0245/Completely_Encapsulated_2026-02-20/pedestal_run/run_20260220_141959/
  run_type: pedestal_run
  serverIP: 192.168.1.144
  zmqPushPull_port: 8888
daq:
  active_menu: randomL1A
  elinks_daq:
  - idcode: 0
    name: link0
    polarity: 1
  - idcode: 1
    name: link1
    polarity: 1
  - idcode: 36
    name: link4
    polarity: 1
  - idcode: 37
    name: link5
    polarity: 1
  - idcode: 72
    name: link8
    polarity: 1
  - idcode: 73
    name: link9
    polarity: 1
  elinks_trg:
  - idcode: 2
    name: link0
    polarity: 1
  - idcode: 1
    name: link1
    polarity: 0
  - idcode: 0
    name: link2
    polarity: 1
  - idcode: 3
    name: link3
    polarity: 0
  - idcode: 36
    name: link4
    polarity: 0
  - idcode: 37
    name: link5
    polarity: 1
  - idcode: 38
    name: link6
    polarity: 0
  - idcode: 39
    name: link7
    polarity: 1
  - idcode: 72
    name: link8
    polarity: 1
  - idcode: 73
    name: link9
    polarity: 1
  - idcode: 74
    name: link10
    polarity: 1
  - idcode: 75
    name: link11
    polarity: 1
  elinks_trg_phase:
  - idcode: 1
    name: link0
    polarity: 1
  l1aOffsetFinder:
    L1A_offset_or_BX: 13
    fifo_latency: 0
    method: automatic
  menus:
    calibAndL1A:
      NEvents: 1000
      bxCalib: 10
      bxL1A: 33
      lengthCalib: 1
      lengthL1A: 1
      prescale: 0
      repeatOffset: 700
    calibAndL1AplusTPG:
      NEvents: 1000
      bxCalib: 10
      bxL1A: 33
      lengthCalib: 1
      lengthL1A: 1
      prescale: 0
      trg_fifo_latency: 3
    calibExtAndcalibIntAndL1A:
      NEvents: 1000
      bxCalibExt: 0
      bxCalibInt: 10
      bxL1A: 33
      lengthCalibExt: 1
      lengthL1A: 1
      prescale: 0
      repeatOffset: 700
    delayScan:
      acquireLength: 1000
      delayStep: 1
      idlePattern: 0XACCCCCCC
      maxDelay: 512
    externalL1A:
      NEvents: 10000
      bxCalibExt: 10
      lengthCalibExt: 2
      loopBack: true
      prescale: 0
      trg_fifo_latency: 3
      trgphase_fifo_latency: 15
    externalL1AOnlyDAQ:
      NEvents: 10000
      bxCalibExt: 10
      lengthCalibExt: 2
      loopBack: true
      prescale: 0
      trgphase_fifo_latency: 15
    marsCalibAndL1A:
      bxCalib: 10
      bxL1A: 45
      prescale: 0
      repeatOffset: 200
    marsRndL1A:
      bx_min: 45
      log2_rand_bx_period: 10
    randomL1A:
      NEvents: 10000
      bx_min: 45
      log2_rand_bx_period: 0
    randomL1AplusTPG:
      NEvents: 10000
      bx_min: 45
      log2_rand_bx_period: 10
      trg_fifo_latency: 3
  zmqPushPull_port: 8888
roc_s0:
  sc:
    DigitalHalf:
      0:
        Bx_offset: 2
        CalibrationSC: 1
        IdleFrame: 214748364
        L1Offset: 10
      1:
        Bx_offset: 2
        CalibrationSC: 1
        IdleFrame: 214748364
        L1Offset: 10
    GlobalAnalog:
      0:
        Cf: 4
        Cf_comp: 2
        Delay40: 2
        Delay65: 3
        Delay87: 3
        Delay9: 3
        Ibi_inv_buf: 0
        Ibi_noinv_buf: 0
        Ibo_inv_buf: 12
        Ibo_noinv_buf: 12
        Rf: 5
        dac_hyst_toa: 15
        dac_pol: 0
        en_deglitcher: 1
        range_inv: 6
        range_tot: 7
        trim_vbi_pa: 15
      1:
        Cf: 4
        Cf_comp: 2
        Delay40: 2
        Delay65: 3
        Delay87: 3
        Delay9: 3
        Ibi_inv_buf: 0
        Ibi_noinv_buf: 0
        Ibo_inv_buf: 12
        Ibo_noinv_buf: 12
        Rf: 5
        dac_hyst_toa: 15
        dac_pol: 0
        en_deglitcher: 1
        range_inv: 6
        range_tot: 7
        trim_vbi_pa: 15
    MasterTdc:
      0:
        BIAS_CAL_DAC_CTDC_P_D: 2
        BIAS_CAL_DAC_CTDC_P_EN: 1
        BIAS_FOLLOWER_CAL_P_CTDC_D: 4
        BIAS_FOLLOWER_CAL_P_CTDC_EN: 1
        BIAS_FOLLOWER_CAL_P_FTDC_D: 4
        BIAS_FOLLOWER_CAL_P_FTDC_EN: 1
        BIAS_I_CTDC_D: 8
        BIAS_I_FTDC_D: 8
        CTDC_CALIB_FREQUENCY: 2
        CTRL_IN_CTDC_P_D: 0
        CTRL_IN_CTDC_P_EN: 0
        EN_MASTER_CTDC_VOUT_INIT: 0
        EN_MASTER_FTDC_VOUT_INIT: 0
        FOLLOWER_CTDC_EN: 1
        FOLLOWER_FTDC_EN: 1
        FTDC_CALIB_FREQUENCY: 2
        GLOBAL_EN_BUFFER_CTDC: 1
        GLOBAL_EN_BUFFER_FTDC: 1
        GLOBAL_LATENCY_TIME: 9
        GLOBAL_SYNC_OUT: 1
        VD_CTDC_P_D: 16
        VD_CTDC_P_DAC_EN: 1
        VD_FTDC_P_D: 16
        VD_FTDC_P_DAC_EN: 1
      1:
        BIAS_CAL_DAC_CTDC_P_D: 2
        BIAS_CAL_DAC_CTDC_P_EN: 1
        BIAS_FOLLOWER_CAL_P_CTDC_D: 4
        BIAS_FOLLOWER_CAL_P_CTDC_EN: 1
        BIAS_FOLLOWER_CAL_P_FTDC_D: 4
        BIAS_FOLLOWER_CAL_P_FTDC_EN: 1
        BIAS_I_CTDC_D: 8
        BIAS_I_FTDC_D: 8
        CTDC_CALIB_FREQUENCY: 2
        CTRL_IN_CTDC_P_D: 0
        CTRL_IN_CTDC_P_EN: 0
        EN_MASTER_CTDC_VOUT_INIT: 0
        EN_MASTER_FTDC_VOUT_INIT: 0
        FOLLOWER_CTDC_EN: 1
        FOLLOWER_FTDC_EN: 1
        FTDC_CALIB_FREQUENCY: 2
        GLOBAL_EN_BUFFER_CTDC: 1
        GLOBAL_EN_BUFFER_FTDC: 1
        GLOBAL_LATENCY_TIME: 9
        GLOBAL_SYNC_OUT: 1
        VD_CTDC_P_D: 16
        VD_CTDC_P_DAC_EN: 1
        VD_FTDC_P_D: 16
        VD_FTDC_P_DAC_EN: 1
    ReferenceVoltage:
      0:
        Inv_vref: 440
        Noinv_vref: 204
        Refi: 1
        Toa_vref: 1023
        Tot_vref: 500
        Vbg_1v: 3
      1:
        Inv_vref: 436
        Noinv_vref: 174
        Refi: 1
        Toa_vref: 1023
        Tot_vref: 500
        Vbg_1v: 3
    Top:
      0:
        BIAS_I_PLL_D: 63
        EN_HIGH_CAPA: 1
        RunL: 1
        RunR: 1
        in_inv_cmd_rx: 1
        phase_ck: 0
    calib:
      0:
        trim_inv: 33
      1:
        trim_inv: 21
    ch:
      0:
        trim_inv: 35
      1:
        trim_inv: 17
      2:
        trim_inv: 14
      3:
        trim_inv: 13
      4:
        trim_inv: 20
      5:
        trim_inv: 21
      6:
        trim_inv: 23
      7:
        trim_inv: 16
      8:
        trim_inv: 16
      9:
        trim_inv: 38
      10:
        trim_inv: 19
      11:
        trim_inv: 19
      12:
        trim_inv: 38
      13:
        trim_inv: 44
      14:
        trim_inv: 30
      15:
        trim_inv: 2
      16:
        trim_inv: 38
      17:
        HZ_inv: 0
        HZ_noinv: 0
        trim_inv: 32
      18:
        trim_inv: 15
      19:
        trim_inv: 39
      20:
        trim_inv: 27
      21:
        trim_inv: 23
      22:
        trim_inv: 16
      23:
        trim_inv: 25
      24:
        trim_inv: 41
      25:
        trim_inv: 0
      26:
        trim_inv: 47
      27:
        trim_inv: 50
      28:
        trim_inv: 44
      29:
        trim_inv: 22
      30:
        trim_inv: 33
      31:
        trim_inv: 31
      32:
        trim_inv: 24
      33:
        trim_inv: 42
      34:
        trim_inv: 43
      35:
        trim_inv: 50
      36:
        trim_inv: 20
      37:
        trim_inv: 38
      38:
        trim_inv: 0
      39:
        trim_inv: 22
      40:
        trim_inv: 33
      41:
        trim_inv: 22
      42:
        trim_inv: 12
      43:
        trim_inv: 25
      44:
        trim_inv: 29
      45:
        trim_inv: 5
      46:
        trim_inv: 21
      47:
        trim_inv: 54
      48:
        trim_inv: 26
      49:
        trim_inv: 30
      50:
        trim_inv: 19
      51:
        trim_inv: 49
      52:
        trim_inv: 24
      53:
        HZ_inv: 0
        HZ_noinv: 0
        trim_inv: 40
      54:
        trim_inv: 26
      55:
        trim_inv: 19
      56:
        trim_inv: 10
      57:
        trim_inv: 2
      58:
        trim_inv: 58
      59:
        trim_inv: 33
      60:
        trim_inv: 12
      61:
        trim_inv: 6
      62:
        trim_inv: 15
      63:
        trim_inv: 27
      64:
        trim_inv: 13
      65:
        trim_inv: 17
      66:
        trim_inv: 21
      67:
        trim_inv: 34
      68:
        trim_inv: 12
      69:
        trim_inv: 16
      70:
        trim_inv: 24
      71:
        trim_inv: 32
    cm:
      0:
        trim_inv: 14
      1:
        trim_inv: 23
      2:
        trim_inv: 33
      3:
        trim_inv: 19
roc_s1:
  sc:
    DigitalHalf:
      0:
        Bx_offset: 2
        CalibrationSC: 1
        IdleFrame: 214748364
        L1Offset: 10
      1:
        Bx_offset: 2
        CalibrationSC: 1
        IdleFrame: 214748364
        L1Offset: 10
    GlobalAnalog:
      0:
        Cf: 4
        Cf_comp: 2
        Delay40: 2
        Delay65: 3
        Delay87: 3
        Delay9: 3
        Ibi_inv_buf: 0
        Ibi_noinv_buf: 0
        Ibo_inv_buf: 12
        Ibo_noinv_buf: 12
        Rf: 5
        dac_hyst_toa: 15
        dac_pol: 0
        en_deglitcher: 1
        range_inv: 6
        range_tot: 7
        trim_vbi_pa: 15
      1:
        Cf: 4
        Cf_comp: 2
        Delay40: 2
        Delay65: 3
        Delay87: 3
        Delay9: 3
        Ibi_inv_buf: 0
        Ibi_noinv_buf: 0
        Ibo_inv_buf: 12
        Ibo_noinv_buf: 12
        Rf: 5
        dac_hyst_toa: 15
        dac_pol: 0
        en_deglitcher: 1
        range_inv: 6
        range_tot: 7
        trim_vbi_pa: 15
    MasterTdc:
      0:
        BIAS_CAL_DAC_CTDC_P_D: 2
        BIAS_CAL_DAC_CTDC_P_EN: 1
        BIAS_FOLLOWER_CAL_P_CTDC_D: 4
        BIAS_FOLLOWER_CAL_P_CTDC_EN: 1
        BIAS_FOLLOWER_CAL_P_FTDC_D: 4
        BIAS_FOLLOWER_CAL_P_FTDC_EN: 1
        BIAS_I_CTDC_D: 8
        BIAS_I_FTDC_D: 8
        CTDC_CALIB_FREQUENCY: 2
        CTRL_IN_CTDC_P_D: 0
        CTRL_IN_CTDC_P_EN: 0
        EN_MASTER_CTDC_VOUT_INIT: 0
        EN_MASTER_FTDC_VOUT_INIT: 0
        FOLLOWER_CTDC_EN: 1
        FOLLOWER_FTDC_EN: 1
        FTDC_CALIB_FREQUENCY: 2
        GLOBAL_EN_BUFFER_CTDC: 1
        GLOBAL_EN_BUFFER_FTDC: 1
        GLOBAL_LATENCY_TIME: 9
        GLOBAL_SYNC_OUT: 1
        VD_CTDC_P_D: 16
        VD_CTDC_P_DAC_EN: 1
        VD_FTDC_P_D: 16
        VD_FTDC_P_DAC_EN: 1
      1:
        BIAS_CAL_DAC_CTDC_P_D: 2
        BIAS_CAL_DAC_CTDC_P_EN: 1
        BIAS_FOLLOWER_CAL_P_CTDC_D: 4
        BIAS_FOLLOWER_CAL_P_CTDC_EN: 1
        BIAS_FOLLOWER_CAL_P_FTDC_D: 4
        BIAS_FOLLOWER_CAL_P_FTDC_EN: 1
        BIAS_I_CTDC_D: 8
        BIAS_I_FTDC_D: 8
        CTDC_CALIB_FREQUENCY: 2
        CTRL_IN_CTDC_P_D: 0
        CTRL_IN_CTDC_P_EN: 0
        EN_MASTER_CTDC_VOUT_INIT: 0
        EN_MASTER_FTDC_VOUT_INIT: 0
        FOLLOWER_CTDC_EN: 1
        FOLLOWER_FTDC_EN: 1
        FTDC_CALIB_FREQUENCY: 2
        GLOBAL_EN_BUFFER_CTDC: 1
        GLOBAL_EN_BUFFER_FTDC: 1
        GLOBAL_LATENCY_TIME: 9
        GLOBAL_SYNC_OUT: 1
        VD_CTDC_P_D: 16
        VD_CTDC_P_DAC_EN: 1
        VD_FTDC_P_D: 16
        VD_FTDC_P_DAC_EN: 1
    ReferenceVoltage:
      0:
        Inv_vref: 437
        Noinv_vref: 264
        Refi: 1
        Toa_vref: 1023
        Tot_vref: 500
        Vbg_1v: 3
      1:
        Inv_vref: 454
        Noinv_vref: 226
        Refi: 1
        Toa_vref: 1023
        Tot_vref: 500
        Vbg_1v: 3
    Top:
      0:
        BIAS_I_PLL_D: 63
        EN_HIGH_CAPA: 1
        RunL: 1
        RunR: 1
        in_inv_cmd_rx: 1
        phase_ck: 0
    calib:
      0:
        trim_inv: 28
      1:
        trim_inv: 27
    ch:
      0:
        trim_inv: 39
      1:
        trim_inv: 32
      2:
        trim_inv: 20
      3:
        trim_inv: 3
      4:
        trim_inv: 12
      5:
        trim_inv: 33
      6:
        trim_inv: 34
      7:
        trim_inv: 21
      8:
        trim_inv: 20
      9:
        trim_inv: 1
      10:
        trim_inv: 9
      11:
        trim_inv: 23
      12:
        trim_inv: 15
      13:
        trim_inv: 10
      14:
        trim_inv: 53
      15:
        trim_inv: 39
      16:
        trim_inv: 42
      17:
        HZ_inv: 0
        HZ_noinv: 0
        trim_inv: 1
      18:
        trim_inv: 9
      19:
        trim_inv: 19
      20:
        trim_inv: 1
      21:
        trim_inv: 1
      22:
        trim_inv: 40
      23:
        trim_inv: 36
      24:
        trim_inv: 39
      25:
        trim_inv: 16
      26:
        trim_inv: 13
      27:
        trim_inv: 24
      28:
        trim_inv: 26
      29:
        trim_inv: 33
      30:
        trim_inv: 17
      31:
        trim_inv: 14
      32:
        trim_inv: 41
      33:
        trim_inv: 0
      34:
        trim_inv: 24
      35:
        trim_inv: 29
      36:
        trim_inv: 0
      37:
        trim_inv: 13
      38:
        trim_inv: 33
      39:
        trim_inv: 19
      40:
        trim_inv: 23
      41:
        trim_inv: 30
      42:
        trim_inv: 30
      43:
        trim_inv: 18
      44:
        trim_inv: 32
      45:
        trim_inv: 17
      46:
        trim_inv: 18
      47:
        trim_inv: 41
      48:
        trim_inv: 45
      49:
        trim_inv: 36
      50:
        trim_inv: 0
      51:
        trim_inv: 33
      52:
        trim_inv: 18
      53:
        HZ_inv: 0
        HZ_noinv: 0
        trim_inv: 27
      54:
        trim_inv: 23
      55:
        trim_inv: 33
      56:
        trim_inv: 38
      57:
        trim_inv: 53
      58:
        trim_inv: 19
      59:
        trim_inv: 26
      60:
        trim_inv: 36
      61:
        trim_inv: 21
      62:
        trim_inv: 30
      63:
        trim_inv: 30
      64:
        trim_inv: 42
      65:
        trim_inv: 25
      66:
        trim_inv: 33
      67:
        trim_inv: 20
      68:
        trim_inv: 14
      69:
        trim_inv: 39
      70:
        trim_inv: 24
      71:
        trim_inv: 39
    cm:
      0:
        trim_inv: 51
      1:
        trim_inv: 15
      2:
        trim_inv: 0
      3:
        trim_inv: 13
roc_s2:
  sc:
    DigitalHalf:
      0:
        Bx_offset: 2
        CalibrationSC: 1
        IdleFrame: 214748364
        L1Offset: 10
      1:
        Bx_offset: 2
        CalibrationSC: 1
        IdleFrame: 214748364
        L1Offset: 10
    GlobalAnalog:
      0:
        Cf: 4
        Cf_comp: 2
        Delay40: 2
        Delay65: 3
        Delay87: 3
        Delay9: 3
        Ibi_inv_buf: 0
        Ibi_noinv_buf: 0
        Ibo_inv_buf: 12
        Ibo_noinv_buf: 12
        Rf: 5
        dac_hyst_toa: 15
        dac_pol: 0
        en_deglitcher: 1
        range_inv: 6
        range_tot: 7
        trim_vbi_pa: 15
      1:
        Cf: 4
        Cf_comp: 2
        Delay40: 2
        Delay65: 3
        Delay87: 3
        Delay9: 3
        Ibi_inv_buf: 0
        Ibi_noinv_buf: 0
        Ibo_inv_buf: 12
        Ibo_noinv_buf: 12
        Rf: 5
        dac_hyst_toa: 15
        dac_pol: 0
        en_deglitcher: 1
        range_inv: 6
        range_tot: 7
        trim_vbi_pa: 15
    MasterTdc:
      0:
        BIAS_CAL_DAC_CTDC_P_D: 2
        BIAS_CAL_DAC_CTDC_P_EN: 1
        BIAS_FOLLOWER_CAL_P_CTDC_D: 4
        BIAS_FOLLOWER_CAL_P_CTDC_EN: 1
        BIAS_FOLLOWER_CAL_P_FTDC_D: 4
        BIAS_FOLLOWER_CAL_P_FTDC_EN: 1
        BIAS_I_CTDC_D: 8
        BIAS_I_FTDC_D: 8
        CTDC_CALIB_FREQUENCY: 2
        CTRL_IN_CTDC_P_D: 0
        CTRL_IN_CTDC_P_EN: 0
        EN_MASTER_CTDC_VOUT_INIT: 0
        EN_MASTER_FTDC_VOUT_INIT: 0
        FOLLOWER_CTDC_EN: 1
        FOLLOWER_FTDC_EN: 1
        FTDC_CALIB_FREQUENCY: 2
        GLOBAL_EN_BUFFER_CTDC: 1
        GLOBAL_EN_BUFFER_FTDC: 1
        GLOBAL_LATENCY_TIME: 9
        GLOBAL_SYNC_OUT: 1
        VD_CTDC_P_D: 16
        VD_CTDC_P_DAC_EN: 1
        VD_FTDC_P_D: 16
        VD_FTDC_P_DAC_EN: 1
      1:
        BIAS_CAL_DAC_CTDC_P_D: 2
        BIAS_CAL_DAC_CTDC_P_EN: 1
        BIAS_FOLLOWER_CAL_P_CTDC_D: 4
        BIAS_FOLLOWER_CAL_P_CTDC_EN: 1
        BIAS_FOLLOWER_CAL_P_FTDC_D: 4
        BIAS_FOLLOWER_CAL_P_FTDC_EN: 1
        BIAS_I_CTDC_D: 8
        BIAS_I_FTDC_D: 8
        CTDC_CALIB_FREQUENCY: 2
        CTRL_IN_CTDC_P_D: 0
        CTRL_IN_CTDC_P_EN: 0
        EN_MASTER_CTDC_VOUT_INIT: 0
        EN_MASTER_FTDC_VOUT_INIT: 0
        FOLLOWER_CTDC_EN: 1
        FOLLOWER_FTDC_EN: 1
        FTDC_CALIB_FREQUENCY: 2
        GLOBAL_EN_BUFFER_CTDC: 1
        GLOBAL_EN_BUFFER_FTDC: 1
        GLOBAL_LATENCY_TIME: 9
        GLOBAL_SYNC_OUT: 1
        VD_CTDC_P_D: 16
        VD_CTDC_P_DAC_EN: 1
        VD_FTDC_P_D: 16
        VD_FTDC_P_DAC_EN: 1
    ReferenceVoltage:
      0:
        Inv_vref: 454
        Noinv_vref: 189
        Refi: 1
        Toa_vref: 1023
        Tot_vref: 500
        Vbg_1v: 3
      1:
        Inv_vref: 444
        Noinv_vref: 217
        Refi: 1
        Toa_vref: 1023
        Tot_vref: 500
        Vbg_1v: 3
    Top:
      0:
        BIAS_I_PLL_D: 63
        EN_HIGH_CAPA: 1
        RunL: 1
        RunR: 1
        in_inv_cmd_rx: 1
        phase_ck: 0
    calib:
      0:
        trim_inv: 49
      1:
        trim_inv: 28
    ch:
      0:
        trim_inv: 19
      1:
        trim_inv: 46
      2:
        trim_inv: 44
      3:
        trim_inv: 32
      4:
        trim_inv: 0
      5:
        trim_inv: 27
      6:
        trim_inv: 31
      7:
        trim_inv: 10
      8:
        trim_inv: 25
      9:
        trim_inv: 11
      10:
        trim_inv: 48
      11:
        trim_inv: 9
      12:
        trim_inv: 18
      13:
        trim_inv: 56
      14:
        trim_inv: 26
      15:
        trim_inv: 26
      16:
        trim_inv: 29
      17:
        HZ_inv: 0
        HZ_noinv: 0
        trim_inv: 44
      18:
        trim_inv: 41
      19:
        trim_inv: 29
      20:
        trim_inv: 25
      21:
        trim_inv: 36
      22:
        trim_inv: 38
      23:
        trim_inv: 24
      24:
        trim_inv: 27
      25:
        trim_inv: 18
      26:
        trim_inv: 28
      27:
        trim_inv: 32
      28:
        trim_inv: 33
      29:
        trim_inv: 27
      30:
        trim_inv: 20
      31:
        trim_inv: 21
      32:
        trim_inv: 41
      33:
        trim_inv: 27
      34:
        trim_inv: 23
      35:
        trim_inv: 21
      36:
        trim_inv: 5
      37:
        trim_inv: 26
      38:
        trim_inv: 30
      39:
        trim_inv: 10
      40:
        trim_inv: 25
      41:
        trim_inv: 63
      42:
        trim_inv: 18
      43:
        trim_inv: 38
      44:
        trim_inv: 37
      45:
        trim_inv: 21
      46:
        trim_inv: 20
      47:
        trim_inv: 4
      48:
        trim_inv: 3
      49:
        trim_inv: 8
      50:
        trim_inv: 14
      51:
        trim_inv: 39
      52:
        trim_inv: 7
      53:
        HZ_inv: 0
        HZ_noinv: 0
        trim_inv: 31
      54:
        trim_inv: 46
      55:
        trim_inv: 20
      56:
        trim_inv: 16
      57:
        trim_inv: 6
      58:
        trim_inv: 19
      59:
        trim_inv: 13
      60:
        trim_inv: 13
      61:
        trim_inv: 22
      62:
        trim_inv: 33
      63:
        trim_inv: 24
      64:
        trim_inv: 4
      65:
        trim_inv: 0
      66:
        trim_inv: 11
      67:
        trim_inv: 4
      68:
        trim_inv: 27
      69:
        trim_inv: 39
      70:
        trim_inv: 33
      71:
        trim_inv: 38
    cm:
      0:
        trim_inv: 34
      1:
        trim_inv: 28
      2:
        trim_inv: 2
      3:
        trim_inv: 22
